version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - "./api:/app"
    ports:
      - "8000:8000"

  proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1-buster
    volumes:
      - ./service_account.json:/config
    ports:
      - 5432:5432
    command: "/cloud_sql_proxy -instances=$GOOGLE_CLOUD_PROJECT:$CLOUD_SQL_REGION:$CLOUD_SQL_INSTANCE_NAME=tcp:0.0.0.0:5432 -credential_file=/config"
