name: API - Deploy to GCP App Engine

on:
  push:
    branches:
      - main

env:
  GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

jobs:
  deploy:
    name: Setup and Deploy to App Engine
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.2"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: "${{ secrets.PROJECT_ID }}"
          service_account_key: "${{ secrets.GCP_SA_KEY }}"
          export_default_credentials: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: collectstatic
        run: python manage.py collectstatic --noinput

      - name: Deploy to App Engine
        run: gcloud app deploy -q
