name: API - Publish to Quay

on:
  push:

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    name: Build and Publish to Quay
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - name: Create env
        run: |
          cat << EOF > .env
          GOOGLE_CLOUD_PROJECT={{ secrets.GOOGLE_CLOUD_PROJECT }}
          SECRET_KEY={{ secrets.SECRET_KEY }}
          APP_ENGINE_URL={{ secrets.APP_ENGINE_URL }}
          POSTGRES_DB={{ secrets.POSTGRES_DB }}
          POSTGRES_USER={{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD={{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST={{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT={{ secrets.POSTGRES_PORT }}
          GOOGLE_CLIENT_ID={{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET={{ secrets.GOOGLE_CLIENT_SECRET }}
          SENDGRID_API_KEY={{ secrets.SENDGRID_API_KEY }}
          SENDGRID_ADMIN_EMAIL={{ secrets.SENDGRID_ADMIN_EMAIL }}
          EOF

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_NIMBUS_USERNAME }}
          password: ${{ secrets.QUAY_NIMBUS_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: nimbusinformatics/bdcat-data-tracker:$GITHUB_SHA
