name: API - Publish to Quay

on: workflow_dispatch

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    name: Build and Publish to Quay
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          cat << EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF

      - name: Create short-sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_NIMBUS_USERNAME }}
          password: ${{ secrets.QUAY_NIMBUS_PASSWORD }}

      - name: Generate Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/nimbusinformatics/bdcat-data-tracker
          tags: |
            ${{ env.SHORT_SHA }}
            latest

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
